# Generated by Django 5.1 on 2024-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('august', models.BooleanField(default=False)),
                ('september', models.BooleanField(default=False)),
                ('october', models.BooleanField(default=False)),
                ('november', models.BooleanField(default=False)),
                ('december', models.BooleanField(default=False)),
                ('january', models.BooleanField(default=False)),
                ('february', models.BooleanField(default=False)),
                ('march', models.BooleanField(default=False)),
                ('april', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
            ],
        ),
    ]
